### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [canelasa/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by canelasa** [comment]
Hi Michael,
At first I wasn't sure what was wrong with the mobile view and I wasn't sure what it was supposed to look like but after adding : meta name="viewport" content="width=device-width, initial-scale=1" into the head, I saw the difference. It looks much better now on mobile. Thank you for your feedback!

**Comment by Mikeysax** [comment]
Nice Job :+1:
